version: '3'
services:
  oracle11g:
    image: jaspeen/oracle-xe-11g
    container_name: oracle11g
    volumes:
      - ~/_docker/oracle_11g:/u01/app/oracle jaspeen/oracle-xe-11g
    ports:
      - 1521:1521
